### ISSUE TITLE
Xiaomi Smart Plug WIFI

### ISSUE THREAD

**Issue by sunnyiiii** [al-one/hass-xiaomi-miot#1781]
### Device model / 设备型号

lumi.plug.v1

### Component version / 插件版本

0.7.19

### HA core version / HA版本

2024.7.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Xiaomi Smart Plug integration fails to upgrade the power usage after Home Assistant Core-2024.2.5.

### Entity attributes / 实体属性

select.lumi_v1_aed5_default_power_on_state - Power On/Off state and control works fine. However, the power usage fails to update 
sensor.lumi_v1_aed5_electric_power

### Home Assistant Logs / 系统日志

2024-07-22 10:39:53.339 ERROR (MainThread) [homeassistant.components.sensor] Platform xiaomi_miot does not generate unique IDs. ID lumi.158d0001716085-3ed40554ecb02d0e5abc9b993ba7b067-power_consumption-3.electric_power-2 is already used by sensor.lumi_v1_6085_electric_power - ignoring sensor.lumi_v1_6085_electric_power
2024-07-22 10:39:53.340 ERROR (MainThread) [homeassistant.components.sensor] Platform xiaomi_miot does not generate unique IDs. ID lumi.158d000183aed5-3ed40554ecb02d0e5abc9b993ba7b067-power_consumption-3.electric_power-2 is already used by sensor.lumi_v1_aed5_electric_power - ignoring sensor.lumi_v1_aed5_electric_power
2024-07-22 10:39:53.340 ERROR (MainThread) [homeassistant.components.sensor] Platform xiaomi_miot does not generate unique IDs. ID lumi.158d00015e7906-3ed40554ecb02d0e5abc9b993ba7b067-power_consumption-3.electric_power-2 is already used by sensor.lumi_v1_7906_electric_power - ignoring sensor.lumi_v1_7906_electric_power
2024-07-22 10:39:53.346 ERROR (MainThread) [homeassistant.components.sensor] Platform xiaomi_miot does not generate unique IDs. ID lumi.158d000114c023-3ed40554ecb02d0e5abc9b993ba7b067-power_consumption-3.electric_power-2 is already used by sensor.lumi_v1_c023_electric_power - ignoring sensor.lumi_v1_c023_electric_power
2024-07-22 10:39:53.366 ERROR (MainThread) [homeassistant.components.sensor] Platform xiaomi_miot does not generate unique IDs. ID lumi.158d000183b02b-3ed40554ecb02d0e5abc9b993ba7b067-power_consumption-3.electric_power-2 is already used by sensor.lumi_v1_b02b_electric_power - ignoring sensor.lumi_v1_b02b_electric_power
2024-07-22 10:39:53.382 ERROR (MainThread) [homeassistant.components.sensor] Platform xiaomi_miot does not generate unique IDs. ID lumi.158d000246aa8c-3ed40554ecb02d0e5abc9b993ba7b067-power_consumption-3.electric_power-2 is already used by sensor.lumi_v1_aa8c_electric_power - ignoring sensor.lumi_v1_aa8c_electric_power

**Comment by sunnyiiii** [comment]
![image](https://github.com/user-attachments/assets/b83bd277-2e07-4339-bc07-56a33c566495)

![image](https://github.com/user-attachments/assets/0322af82-8d2c-432b-8c3a-72e4b5fb0ea7)

**Comment by sunnyiiii** [comment]
The power consumption updates if I reload the miot. Once reloaded, it will never update.

**Comment by rjaros87** [comment]
Hi @sunnyiiii, do you have more than one smart plug?
I was seeing the same logs, and in my case, I removed one of the smart plugs from both HA and the Xiaomi app (cloud). The first plug started reporting parameters normally. After that, I re-added the second smart plug to both the Xiaomi app and HA, and it worked for me.

**Comment by sunnyiiii** [comment]
@rjaros87, Yes, I do have a few of them. I have tried adding new plugs to Xiaomi App. I have the same problem with the newly added plugs.

**Comment by al-one** [comment]
Fixed in beta version.
- https://github.com/al-one/hass-xiaomi-miot/releases/tag/v1.0.0b3

**Comment by sunnyiiii** [comment]
Hi @al-one, thank you for fixing the Lumi power plugs. But the cuco.plug.v3 is not working.

2024-11-23 00:43:07.517 INFO (MainThread) [custom_components.xiaomi_miot.core.device.cuco.plug.v3] Device updated: {'indicator_light-3.mode': None, 'indicator_light.on': True, 'electric_power-11-2': 1, 'physical_controls_locked': False, 'switch.on': True}
2024-11-23 00:43:07.517 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] sensor.cuco_v3_9093_electric_power: Entity state updated: 1
2024-11-23 00:43:07.518 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] switch.cuco_v3_9093_switch: Entity state updated: True
2024-11-23 00:43:07.518 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] switch.cuco_v3_9093_physical_control_locked: Entity state updated: False
2024-11-23 00:43:07.519 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] light.cuco_v3_9093_indicator_light: Entity state updated: True
2024-11-23 00:43:07.519 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] button.cuco_v3_9093_info: Entity state updated: 29 - Washing Machine PM
2024-11-23 00:43:07.520 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.cuco.plug.v3] Finished fetching 68:ab:bc:af:90:93-3ed40554ecb02d0e5abc9b993ba7b067-update_miot_status data in 1.444 seconds (success: True)
2024-11-23 00:43:07.520 DEBUG (MainThread) [custom_components.xiaomi_miot.core.coordinator] 29 - Washing Machine PM(cuco.plug.v3): Coordinator updated: ['68:ab:bc:af:90:93-3ed40554ecb02d0e5abc9b993ba7b067-update_miot_status', <custom_components.xiaomi_miot.core.miot_spec.MiotResults object at 0x7f4896d22120>]

![image](https://github.com/user-attachments/assets/738dd1fb-5439-4202-a42e-a50dfcf8843d)

**Comment by sunnyiiii** [comment]
This is fixed.

**Comment by sunnyiiii** [comment]
Hi @al-one, I have downloaded the latest release v0.7.25, and I don't think it included the fixes in v1.0.0b3. Can you please take a look at this when you have time? In case, you missed it.

**Comment by sunnyiiii** [comment]
Thank you @al-one. Working flawlessly with [v1.0.1]
